### ISSUE TITLE
Tab9 not working with latest builds of WebStorm (2025.2.4 and 2025.3 EAP)

### ISSUE THREAD

**Issue by outlawpractice** [codota/tabnine-intellij#765]
Tab9 pane freezes immediately and never gives a prompt. Clicking on the Test tab does nothing, nor does clicking on the other buttons.
Clicking on the refresh button *sometimes* causes an IDE error:

java.lang.NoSuchMethodError: 'com.intellij.internal.statistic.eventLog.events.EventId1 com.intellij.internal.statistic.eventLog.EventLogGroup.registerEvent$default(com.intellij.internal.statistic.eventLog.EventLogGroup, java.lang.String, com.intellij.internal.statistic.eventLog.events.EventField, java.lang.String, int, java.lang.Object)'
	at com.maddyhome.idea.vim.statistic.ActionTrackerKt.<clinit>(ActionTracker.kt:31)
	at com.maddyhome.idea.vim.statistic.ActionTracker.getGroup(ActionTracker.kt:27)
	at com.intellij.internal.statistic.service.fus.collectors.FUCounterUsageLogger.logRegisteredGroups(FUCounterUsageLogger.java:152)
	at com.intellij.internal.statistic.service.fus.collectors.FUCounterUsageLogger.lambda$new$0(FUCounterUsageLogger.java:71)
	at com.intellij.util.concurrency.Propagation.capturePropagationContext$lambda$0$0(propagation.kt:549)
	at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:305)
	at com.intellij.util.concurrency.Propagation.capturePropagationContext$lambda$0(propagation.kt:547)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:281)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

The input box at the bottom of the pane never show us, so it is not possible to run any queries. Clicking on the Model chooser similarly does nothing.

gz#46958<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/46958'>Zendesk ticket #46958</a>)</i>

**Comment by TzufTabnine** [comment]
Hi, do you still have this issue?

**Comment by outlawpractice** [comment]
No, I sent an update saying it is fixed.

From: TzufTabnine ***@***.***>
Date: Tuesday, November 18, 2025 at 5:55 AM
To: codota/tabnine-intellij ***@***.***>
Cc: Support ***@***.***>, Author ***@***.***>
Subject: Re: [codota/tabnine-intellij] Tab9 not working with latest builds of WebStorm (2025.2.4 and 2025.3 EAP) (Issue #765)

[https://avatars.githubusercontent.com/u/121427912?s=20&v=4]TzufTabnine left a comment (codota/tabnine-intellij#765)<https://github.com/codota/tabnine-intellij/issues/765#issuecomment-3547257230>

Hi, do you still have this issue?
